esphome:
  name: modbus
  friendly_name: Modbus

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: ERROR
  

# Enable Home Assistant API
api:


ota:
  - platform: esphome

web_server:
  version: 3
  local: True


wifi:
  ssid: SCHULLER2
  password: schuller2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Modbus"
    


uart:
  id: mod_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 38400
  parity: EVEN
  stop_bits: 1
  data_bits: 8
  rx_buffer_size: 512  
  


modbus:
  id: modbus1
  uart_id: mod_bus
  #send_wait_time: 300ms
      
    
  

modbus_controller:
  id: ESP_WP_Steuerung
  modbus_id: modbus1
  update_interval: 5s
  address: 0x0C
  #setup_priority: -10

sensor: !include { file: gen/danfoss-optyma_sensor.yaml, vars: {modbus: "ESP_WP_Steuerung"}}

binary_sensor: !include { file: gen/danfoss-optyma_binary_sensor.yaml, vars: {modbus: "ESP_WP_Steuerung"}}

number: !include { file: gen/danfoss-optyma_number.yaml, vars: {modbus: "ESP_WP_Steuerung"}}

switch: !include { file: gen/danfoss-optyma_switch.yaml, vars: {modbus: "ESP_WP_Steuerung"}}

